
export const permissions = [
  'dashboard.view',
  'users.view',
  'users.create',
  'users.edit',
  'users.delete',
  'roles.view',
  'roles.manage',
  'settings.view',
  'settings.edit',
  'analytics.view',
  'reports.view',
  'reports.export',
  'courses.view',
  'courses.create',
  'courses.edit',
  'courses.delete',
  'courses.approve',
  'categories.view',
  'categories.create',
  'categories.edit',
  'categories.delete',
  'languages.view',
  'languages.create',
  'languages.edit',
  'languages.delete',
  'teacher_courses.view',
  'teacher_courses.create',
  'teacher_courses.update',
  'teacher_courses.approve',
  'teacher_courses.delete',
  'students.view',
  'students.create',
  'students.edit',
  'students.delete',
  'teachers.view',
  'teachers.manage',
  'profile.view',
  'profile.edit',
  'profile.own',
];

export const rolePermissions = {
  super_admin: [...permissions],
  admin: [
    'dashboard.view',
    'users.view',
    'users.create',
    'users.edit',
    'users.delete',
    'settings.view',
    'settings.edit',
    'analytics.view',
    'reports.view',
    'reports.export',
    'courses.view',
    'courses.create',
    'courses.edit',
    'courses.delete',
    'courses.approve',
    'categories.view',
    'categories.create',
    'categories.edit',
    'categories.delete',
    'languages.view',
    'languages.create',
    'languages.edit',
    'languages.delete',
    'teacher_courses.view',
    'teacher_courses.approve',
    'teacher_courses.delete',
    'students.view',
    'students.create',
    'students.edit',
    'students.delete',
    'teachers.view',
    'teachers.manage',
    'profile.view',
    'profile.edit',
  ],
  teacher: [
    'dashboard.view',
    'courses.view',
    'courses.create',
    'categories.view',
    'languages.view',
    'teacher_courses.view',
    'teacher_courses.create',
    'teacher_courses.update',
    'teacher_courses.delete',
    'students.view',
    'profile.view',
    'profile.edit',
    'profile.own',
  ],
};

export const hasPermission = (role, permission) => rolePermissions[role]?.includes(permission) || false;

